### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by CodeLit** [Timo972/altv-updater-js#5]
` node server_updater.js `

> (node:3506) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> (Use `node --trace-warnings ...` to show where the warning was created)
> /Users/vladimir/Desktop/Projects/gta-server/node_modules/altv-srv/dist/index.esm.js:1
> import{Octokit as R}from"@octokit/core";var G=new R;function j(t,e){let o=t.assets.find(r=>r.name==e);return o==null?null:o.browser_download_url}async function $(t,e,o){try{let r=await G.request("GET /repos/{owner}/{repo}/releases",
> 
> _... removed part of the obfuscated code_
> 
> l=m(t,r);u(l)&&await g(l)}};export{O as hardRegistry,oe as install,le as remove};
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at Object.compileFunction (node:vm:352:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1033:15)
>     at Module._compile (node:internal/modules/cjs/loader:1069:27)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
>     at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
> 

My server_updater.js:

```
import * as server from 'altv-srv';

await server.install("../", "release", ["server", "js"]);
```

**Comment by CodeLit** [comment]
And i also have "type": "module" in my package.json file

**Comment by CodeLit** [comment]
Looks like its my node issue. I just added  "type": "module" in your altv-srv package and its works fine. Now i have this error:

> 
> SyntaxError: Named export 'dirAsync' not found. The requested module 'fs-jetpack' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from 'fs-jetpack';
>

**Comment by CodeLit** [comment]
If you have any idea of how to fix this issue, let me know. Thanks!

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/37398131/180648288-d9345498-d098-4fc7-a34f-5d712a7e3233.png">

**Comment by Timo972** [comment]
have you tried using
```js
import pkg from 'altv-srv';
const { install } = pkg;
```

like the error message suggests?

**Comment by CodeLit** [comment]
Yes. I tried this first

**Comment by Timo972** [comment]
you can consider using the cli until i got time to fix this cjs problem.
your server_updater.js file seems to just invoke the install function which ``npx altv-srv install release -d ../ `` does too.

**Comment by CodeLit** [comment]
Thanks!
